
-------------------------------
elementType: OutOfTestErrors
issues:
  - name: out of test
    infoType: OutOfTest
    warnings:
      - timestamp: '2017-11-25 11:28:22'
        level: warn
        subType: Message
        message: warning added for testing
    errors:
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: Message
        popControl: NoAction
        message: bodged out of test example failure
        additionalInfo: blahh
    type2Errors: []
    knownDefects: []

-------------------------------
summary: |-
  ==== Notes ====
   			licence correct version incorrect - dob differs - [DriverCheck: Invalid driver licence details entered]

   ==== Cache Prior to Request (DB) ====

   ==== Enquiry Properties ====
         productCode: CLC3
         firstName: Helen
         otherName: May
         surname: Ayto
         dateOfBirth: 29/07/1938
         number: AA277022
         version: 845
         enquiryType: 2

   ==== Cache After Request (DB) ====

   ==== Components After Request (DB) ====

   ==== NZTA Log (DB) ====
         id: 137
         NZTAReference: bccbe88d-da99-4da3-af5a-5a4de0476358
         requestStart: 2017-08-21 17:19:57.1473649
         requestDuration: 936
         request:
            RequestBody:
               CustomerDetails:
                  NameDetails:
                     PersonName:
                        LastName: Ayto
                        FirstName: Helen
                        MiddleName: May
                  PersonInfo:
                     BirthInfo:
                        BirthDate:
                           Date: 1938-07-29
         response:
            ResponseBody:

   ==== B2B Response - Driver's Licence Info ====
         Error: Invalid driver licence details entered

startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:27'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Another_Demo_Case
  id: 2
  when: i test anther case
  then: it still works
  owner: JW
  enabled: true
  countries:
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 1
  when: I run a test
  then: i get the result
  validators: check_has_another
apState: {}
passedValidators: []
issues:
  - name: Executing Interactor
    infoType: InTest
    warnings:
      - timestamp: '2017-11-25 11:28:22'
        level: warn
        subType: Message
        message: Warning added for testing in iteration
    errors: []
    type2Errors: []
    knownDefects: []
  - name: check_has_another
    infoType: Validation
    warnings: []
    errors:
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: CheckFail
        popControl: NoAction
        message: Check Text Contains ~ 2 errors 1 iteration
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: CheckFail
        popControl: NoAction
        message: Check Text Contains
        additionalInfo: |-
          Looking for: another
           in
          I run a test
        callstack: |2-
              at Object.logWithlabel [as logError] (C:/ZWTF/src/lib/Logging.js:379:24)
              at logError (C:/ZWTF/src/lib/Logging.js:42:95)
              at logSpecial (C:/ZWTF/src/lib/Logging.js:153:5)
              at genericCheck (C:/ZWTF/src/lib/CheckUtils.js:90:3)
              at checkTextContains (C:/ZWTF/src/lib/CheckUtils.js:48:10)
              at check_has_another (C:/ZWTF/testCases/Another_Demo_Case.js:62:3)
              at validate (C:/ZWTF/src/lib/TestRunner.js:99:7)
              at Array.forEach (native)
              at runValidators (C:/ZWTF/src/lib/TestRunner.js:105:14)
              at C:/ZWTF/src/lib/TestRunner.js:148:29
              at exStage (C:/ZWTF/src/lib/TestRunner.js:117:5)
              at runTestItem (C:/ZWTF/src/lib/TestRunner.js:148:15)
              at C:/ZWTF/src/lib/TestRunner.js:171:30
              at Array.forEach (native)
              at runTest (C:/ZWTF/src/lib/TestRunner.js:171:12)
              at runTestInstance (C:/ZWTF/src/lib/TestRunner.js:237:7)
              at Array.forEach (native)
              at testRun (C:/ZWTF/src/lib/TestRunner.js:241:14)
              at run (C:/ZWTF/testCases/ProjectConfig.js:111:3)
              at Context.<anonymous> (C:/ZWTF/src/test/ProjectConfig.integration.js:23:5)
              at callFn (C:\ZWTF\node_modules\mocha\lib\runnable.js:348:21)
              at Test.Runnable.run (C:\ZWTF\node_modules\mocha\lib\runnable.js:340:7)
              at Runner.runTest (C:\ZWTF\node_modules\mocha\lib\runner.js:443:10)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:549:12
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:361:14)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:371:7
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:295:14)
              at Immediate.<anonymous> (C:\ZWTF\node_modules\mocha\lib\runner.js:339:5)
              at runCallback (timers.js:800:20)
              at tryOnImmediate (timers.js:762:5)
              at processImmediate [as _immediateCallback] (timers.js:733:5)
    type2Errors: []
    knownDefects: []

-------------------------------
summary: Summary not implemented
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Another_Demo_Case
  id: 2
  when: i test anther case
  then: it still works
  owner: JW
  enabled: true
  countries:
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 2
  when: I run another test
  then: i get another result
  validators: check_has_another
apState: {}
passedValidators:
  - check_has_another
issues: []

-------------------------------
elementType: OutOfTestErrors
issues:
  - name: out of test
    infoType: OutOfTest
    warnings:
      - timestamp: '2017-11-25 11:28:22'
        level: warn
        subType: Message
        message: out of test warning 2
    errors: []
    type2Errors:
      - timestamp: '2017-11-25 11:28:22'
        level: info
        subType: EndDefect
        additionalInfo: |
          message: out of test type 2 error
          additionalInfo: |
            active: true
    knownDefects: []

-------------------------------
summary: Summary not implemented
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Demo_Case
  id: 1
  when: I cannot think of anything
  then: I just write something
  owner: JW
  enabled: true
  countries:
    - New Zealand
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 1
  when: I run a test
  then: i get the result
  validators:
    - check_less_than_2
    - check_with_disabled_expectation
    - check_with_incorrect_disabled_expectation
apState: {}
passedValidators:
  - check_with_disabled_expectation
issues:
  - name: check_less_than_2
    infoType: Validation
    warnings: []
    errors: []
    type2Errors:
      - timestamp: '2017-11-25 11:28:22'
        level: info
        subType: EndDefect
        popControl: NoAction
        message: End Defect
        additionalInfo: |
          message: 'Defect Expected: 1'
          additionalInfo: |
            active: true
    knownDefects: []
  - name: check_with_incorrect_disabled_expectation
    infoType: Validation
    warnings: []
    errors:
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: CheckFail
        popControl: NoAction
        message: 'Check False: false is true'
        callstack: |2-
              at Object.logWithlabel [as logError] (C:/ZWTF/src/lib/Logging.js:379:24)
              at logError (C:/ZWTF/src/lib/Logging.js:42:95)
              at logSpecial (C:/ZWTF/src/lib/Logging.js:153:5)
              at genericCheck (C:/ZWTF/src/lib/CheckUtils.js:90:3)
              at checkFalse (C:/ZWTF/src/lib/CheckUtils.js:11:93)
              at check_with_incorrect_disabled_expectation (C:/ZWTF/testCases/Demo_Case.js:87:3)
              at validate (C:/ZWTF/src/lib/TestRunner.js:99:7)
              at Array.forEach (native)
              at runValidators (C:/ZWTF/src/lib/TestRunner.js:105:14)
              at C:/ZWTF/src/lib/TestRunner.js:148:29
              at exStage (C:/ZWTF/src/lib/TestRunner.js:117:5)
              at runTestItem (C:/ZWTF/src/lib/TestRunner.js:148:15)
              at C:/ZWTF/src/lib/TestRunner.js:171:30
              at Array.forEach (native)
              at runTest (C:/ZWTF/src/lib/TestRunner.js:171:12)
              at runTestInstance (C:/ZWTF/src/lib/TestRunner.js:237:7)
              at Array.forEach (native)
              at testRun (C:/ZWTF/src/lib/TestRunner.js:241:14)
              at run (C:/ZWTF/testCases/ProjectConfig.js:111:3)
              at Context.<anonymous> (C:/ZWTF/src/test/ProjectConfig.integration.js:23:5)
              at callFn (C:\ZWTF\node_modules\mocha\lib\runnable.js:348:21)
              at Test.Runnable.run (C:\ZWTF\node_modules\mocha\lib\runnable.js:340:7)
              at Runner.runTest (C:\ZWTF\node_modules\mocha\lib\runner.js:443:10)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:549:12
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:361:14)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:371:7
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:295:14)
              at Immediate.<anonymous> (C:\ZWTF\node_modules\mocha\lib\runner.js:339:5)
              at runCallback (timers.js:800:20)
              at tryOnImmediate (timers.js:762:5)
              at processImmediate [as _immediateCallback] (timers.js:733:5)
    type2Errors: []
    knownDefects: []

-------------------------------
summary: Summary not implemented
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Demo_Case
  id: 1
  when: I cannot think of anything
  then: I just write something
  owner: JW
  enabled: true
  countries:
    - New Zealand
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 2
  when: I run another test
  then: i get another result
  validators:
    - check_less_than_2
    - check_less_than_3
apState: {}
passedValidators:
  - check_less_than_2
  - check_less_than_3
issues: []

-------------------------------
summary: ''
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Demo_Case
  id: 1
  when: I cannot think of anything
  then: I just write something
  owner: JW
  enabled: true
  countries:
    - New Zealand
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 3
  when: I run another test
  then: i get another result
  validators: check_bad_validator
apState: {}
passedValidators: []
issues:
  - name: check_bad_validator
    infoType: Validation
    warnings: []
    errors:
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: Exception
        popControl: NoAction
        message: Exception Thrown Running Validators
        additionalInfo: |-
          Exception thrown in validator: check_bad_validator
          ARGGGHHHHHH!!!
        callstack: |2-
              at Object.logWithlabel [as logError] (C:/ZWTF/src/lib/Logging.js:379:24)
              at logError (C:/ZWTF/src/lib/Logging.js:42:95)
              at logException (C:/ZWTF/src/lib/Logging.js:78:67)
              at exStage (C:/ZWTF/src/lib/TestRunner.js:120:5)
              at runTestItem (C:/ZWTF/src/lib/TestRunner.js:148:15)
              at C:/ZWTF/src/lib/TestRunner.js:171:30
              at Array.forEach (native)
              at runTest (C:/ZWTF/src/lib/TestRunner.js:171:12)
              at runTestInstance (C:/ZWTF/src/lib/TestRunner.js:237:7)
              at Array.forEach (native)
              at testRun (C:/ZWTF/src/lib/TestRunner.js:241:14)
              at run (C:/ZWTF/testCases/ProjectConfig.js:111:3)
              at Context.<anonymous> (C:/ZWTF/src/test/ProjectConfig.integration.js:23:5)
              at callFn (C:\ZWTF\node_modules\mocha\lib\runnable.js:348:21)
              at Test.Runnable.run (C:\ZWTF\node_modules\mocha\lib\runnable.js:340:7)
              at Runner.runTest (C:\ZWTF\node_modules\mocha\lib\runner.js:443:10)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:549:12
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:361:14)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:371:7
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:295:14)
              at Immediate.<anonymous> (C:\ZWTF\node_modules\mocha\lib\runner.js:339:5)
              at runCallback (timers.js:800:20)
              at tryOnImmediate (timers.js:762:5)
              at processImmediate [as _immediateCallback] (timers.js:733:5)
    type2Errors: []
    knownDefects: []

-------------------------------
summary: ''
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Demo_Case
  id: 1
  when: I cannot think of anything
  then: I just write something
  owner: JW
  enabled: true
  countries:
    - New Zealand
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 4
  when: I run another test
  then: i get another result
  validators: check_bad_validator
apState: {}
passedValidators: []
issues:
  - name: Executing Interactor
    infoType: InTest
    warnings: []
    errors:
      - timestamp: '2017-11-25 11:28:22'
        level: error
        subType: Exception
        popControl: NoAction
        message: Exception Thrown Executing Interactor
        additionalInfo: |-
          I do not like 4

          Error
              at fail (C:/ZWTF/src/lib/SysUtils.js:448:13)
              at Object.interactor (C:/ZWTF/testCases/Demo_Case.js:26:5)
              at C:/ZWTF/src/lib/TestRunner.js:136:49
              at exStage (C:/ZWTF/src/lib/TestRunner.js:117:5)
              at runTestItem (C:/ZWTF/src/lib/TestRunner.js:136:15)
              at C:/ZWTF/src/lib/TestRunner.js:171:30
              at Array.forEach (native)
              at runTest (C:/ZWTF/src/lib/TestRunner.js:171:12)
              at runTestInstance (C:/ZWTF/src/lib/TestRunner.js:237:7)
              at Array.forEach (native)
              at testRun (C:/ZWTF/src/lib/TestRunner.js:241:14)
              at run (C:/ZWTF/testCases/ProjectConfig.js:111:3)
              at Context.<anonymous> (C:/ZWTF/src/test/ProjectConfig.integration.js:23:5)
              at callFn (C:\ZWTF\node_modules\mocha\lib\runnable.js:348:21)
              at Test.Runnable.run (C:\ZWTF\node_modules\mocha\lib\runnable.js:340:7)
              at Runner.runTest (C:\ZWTF\node_modules\mocha\lib\runner.js:443:10)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:549:12
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:361:14)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:371:7
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:295:14)
              at Immediate.<anonymous> (C:\ZWTF\node_modules\mocha\lib\runner.js:339:5)
              at runCallback (timers.js:800:20)
              at tryOnImmediate (timers.js:762:5)
              at processImmediate [as _immediateCallback] (timers.js:733:5)
        callstack: |2-
              at Object.logWithlabel [as logError] (C:/ZWTF/src/lib/Logging.js:379:24)
              at logError (C:/ZWTF/src/lib/Logging.js:42:95)
              at logException (C:/ZWTF/src/lib/Logging.js:78:67)
              at exStage (C:/ZWTF/src/lib/TestRunner.js:120:5)
              at runTestItem (C:/ZWTF/src/lib/TestRunner.js:136:15)
              at C:/ZWTF/src/lib/TestRunner.js:171:30
              at Array.forEach (native)
              at runTest (C:/ZWTF/src/lib/TestRunner.js:171:12)
              at runTestInstance (C:/ZWTF/src/lib/TestRunner.js:237:7)
              at Array.forEach (native)
              at testRun (C:/ZWTF/src/lib/TestRunner.js:241:14)
              at run (C:/ZWTF/testCases/ProjectConfig.js:111:3)
              at Context.<anonymous> (C:/ZWTF/src/test/ProjectConfig.integration.js:23:5)
              at callFn (C:\ZWTF\node_modules\mocha\lib\runnable.js:348:21)
              at Test.Runnable.run (C:\ZWTF\node_modules\mocha\lib\runnable.js:340:7)
              at Runner.runTest (C:\ZWTF\node_modules\mocha\lib\runner.js:443:10)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:549:12
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:361:14)
              at C:\ZWTF\node_modules\mocha\lib\runner.js:371:7
              at next (C:\ZWTF\node_modules\mocha\lib\runner.js:295:14)
              at Immediate.<anonymous> (C:\ZWTF\node_modules\mocha\lib\runner.js:339:5)
              at runCallback (timers.js:800:20)
              at tryOnImmediate (timers.js:762:5)
              at processImmediate [as _immediateCallback] (timers.js:733:5)
    type2Errors: []
    knownDefects: []

-------------------------------
summary: ''
startTime: '2017-11-25 11:28:22'
endTime: '2017-11-25 11:28:22'
valTime: 2017-11-25 11-28-22-346
elementType: InterationInfo
testConfig:
  script: Demo_Case3
  id: 2
  when: i test anther case
  then: it still works
  owner: JW
  enabled: true
  countries:
    - Australia
  environments:
    - TST
  depth: Regression
item:
  id: 1
  when: I run a test
  then: i get the result
  validators: check_has_another
apState: {}
passedValidators: []
issues: []
